changelog:
  exclude:
    labels:
      - skip-changelog
    authors:
      - dependabot
  categories:
    - title: New features
      labels:
        - feature
        - enhancement
    - title: Bug fixes
      labels:
        - bug
        - fix
    - title: Other changes
      labels:
        - "*"
