import { useState, type CSSProperties } from "react";

export type AiTask="generate_request"|"explain_response"|"generate_assertions"|"generate_documentation";
export interface AiAssistRequest { endpoint:string; model:string; secretRef:string; task:AiTask; input:string; context?:string }
export interface AiAssistResponse { content:string; model:string }
export interface AiWorkbenchProps { onAssist:(request:AiAssistRequest)=>Promise<AiAssistResponse>; onPutSecret:(name:string,value:string)=>Promise<void> }

const tasks:Array<{id:AiTask;label:string;description:string}>=[{id:"generate_request",label:"生成请求",description:"从自然语言生成可编辑的 HTTP 请求"},{id:"explain_response",label:"解释响应",description:"定位状态、字段与潜在错误"},{id:"generate_assertions",label:"生成断言",description:"产出稳定的回归检查"},{id:"generate_documentation",label:"生成文档",description:"整理接口说明与示例"}];

export function AiWorkbench({onAssist,onPutSecret}:AiWorkbenchProps){
  const [endpoint,setEndpoint]=useState(()=>localStorage.getItem("apivoy:ai-endpoint")??"https://api.openai.com/v1");const [model,setModel]=useState(()=>localStorage.getItem("apivoy:ai-model")??"gpt-4.1-mini");const [secretRef,setSecretRef]=useState(()=>localStorage.getItem("apivoy:ai-secret-ref")??"ai-provider-key");const [secret,setSecret]=useState("");const [task,setTask]=useState<AiTask>("generate_request");const [input,setInput]=useState("");const [context,setContext]=useState("");const [output,setOutput]=useState("");const [message,setMessage]=useState("");const [loading,setLoading]=useState(false);
  async function saveKey(){if(!secret.trim())return;try{await onPutSecret(secretRef,secret);setSecret("");setMessage(`密钥已安全保存为 ${secretRef}`);}catch(error){setMessage(error instanceof Error?error.message:String(error));}}
  async function run(){setLoading(true);setMessage("");try{localStorage.setItem("apivoy:ai-endpoint",endpoint);localStorage.setItem("apivoy:ai-model",model);localStorage.setItem("apivoy:ai-secret-ref",secretRef);const result=await onAssist({endpoint,model,secretRef,task,input,context:context||undefined});setOutput(result.content);setMessage(`由 ${result.model} 生成 · 请在应用前检查`);}catch(error){setMessage(error instanceof Error?error.message:String(error));}finally{setLoading(false);}}
  function applyRequest(){try{const cleaned=output.replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/,"");const value=JSON.parse(cleaned) as Record<string,unknown>;const headers=Array.isArray(value.headers)?value.headers:[];const request={name:String(value.name??"AI generated request"),method:String(value.method??"GET").toUpperCase(),url:String(value.url??""),headers,body:value.body==null?undefined:String(value.body),timeoutMs:30000,variables:typeof value.variables==="object"&&value.variables?value.variables:{},assertions:[],auth:null,followRedirects:true,retryMax:0,retryBackoffMs:250,proxy:null,tlsVerify:true};window.dispatchEvent(new CustomEvent("apivoy-open-request",{detail:{protocolId:"http",request,aiAssertions:typeof value.assertions==="string"?value.assertions:""}}));setMessage("已应用到 HTTP 工作台，发送前请检查 URL、Headers 与 Body");}catch(error){setMessage(`无法应用：${error instanceof Error?error.message:String(error)}`);}}
  return <section style={styles.root}><header style={styles.header}><div><small style={styles.eyebrow}>LOCAL-FIRST AI COPILOT</small><h2 style={styles.title}>AI 辅助</h2><p style={styles.copy}>自带模型与密钥。上下文只会发送到你配置的提供商，生成结果永远先预览、后应用。</p></div><span style={styles.badge}>BYOK · EXPLICIT</span></header><div style={styles.tasks}>{tasks.map(item=><button key={item.id} style={{...styles.task,...(task===item.id?styles.taskActive:{})}} onClick={()=>setTask(item.id)}><b>{item.label}</b><span>{item.description}</span></button>)}</div><div style={styles.columns}><div style={styles.panel}><h3>模型连接</h3><label style={styles.label}>OPENAI-COMPATIBLE ENDPOINT<input style={styles.input} value={endpoint} onChange={event=>setEndpoint(event.target.value)} /></label><label style={styles.label}>MODEL<input style={styles.input} value={model} onChange={event=>setModel(event.target.value)} /></label><label style={styles.label}>SECRET REF<input style={styles.input} value={secretRef} onChange={event=>setSecretRef(event.target.value)} /></label><div style={styles.secretRow}><input style={styles.input} type="password" placeholder="API Key（不会写入项目）" value={secret} onChange={event=>setSecret(event.target.value)} /><button style={styles.secondary} disabled={!secret.trim()} onClick={()=>void saveKey()}>存入密钥</button></div><div style={styles.safety}>远程地址强制 HTTPS；本机 Ollama/兼容服务可使用 HTTP localhost。</div></div><div style={styles.panel}><h3>任务上下文</h3><label style={styles.label}>INSTRUCTION<textarea style={styles.textarea} value={input} onChange={event=>setInput(event.target.value)} placeholder="例如：创建一个带分页参数的用户列表请求…" /></label><label style={styles.label}>OPTIONAL CONTEXT<textarea style={styles.context} value={context} onChange={event=>setContext(event.target.value)} placeholder="粘贴请求、响应或 Schema；请勿包含明文密钥" /></label><button style={styles.primary} disabled={loading||!input.trim()||!endpoint.trim()||!model.trim()} onClick={()=>void run()}>{loading?"正在生成…":"生成预览"}</button></div></div><div style={styles.output}><div style={styles.outputHeader}><h3>生成结果</h3><div>{task==="generate_request"&&output&&<button style={styles.secondary} onClick={applyRequest}>应用到 HTTP</button>}<button style={styles.ghost} disabled={!output} onClick={()=>void navigator.clipboard.writeText(output)}>复制</button></div></div><pre>{output||"生成结果会显示在这里。ApiVoy 不会自动执行或保存 AI 生成的请求。"}</pre></div>{message&&<div style={styles.notice}>{message}</div>}</section>;
}

const styles:Record<string,CSSProperties>={root:{border:"1px solid var(--apivoy-border)",borderRadius:18,background:"var(--apivoy-panel)",padding:24,minHeight:620},header:{display:"flex",justifyContent:"space-between",gap:20,alignItems:"flex-start",marginBottom:22},eyebrow:{letterSpacing:2,color:"#c68cff",fontSize:10,fontWeight:800},title:{fontSize:28,margin:"5px 0 8px",letterSpacing:-.8},copy:{color:"var(--apivoy-muted)",lineHeight:1.7,maxWidth:680,margin:0},badge:{fontSize:10,letterSpacing:1.2,color:"#d7afff",border:"1px solid rgba(179,88,255,.35)",background:"rgba(179,88,255,.09)",borderRadius:999,padding:"7px 11px",fontWeight:800},tasks:{display:"grid",gridTemplateColumns:"repeat(4,minmax(0,1fr))",gap:8,marginBottom:14},task:{display:"grid",gap:4,textAlign:"left",border:"1px solid var(--apivoy-border)",borderRadius:11,background:"rgba(5,10,16,.42)",color:"var(--apivoy-text)",padding:12,cursor:"pointer"},taskActive:{borderColor:"rgba(179,88,255,.55)",background:"rgba(179,88,255,.1)",boxShadow:"inset 0 0 0 1px rgba(179,88,255,.12)"},columns:{display:"grid",gridTemplateColumns:"minmax(280px,.75fr) minmax(400px,1.25fr)",gap:13},panel:{border:"1px solid var(--apivoy-border)",borderRadius:13,background:"rgba(5,10,16,.5)",padding:16},label:{display:"grid",gap:6,color:"var(--apivoy-muted)",fontSize:10,fontWeight:700,marginBottom:11},input:{width:"100%",border:"1px solid var(--apivoy-border)",borderRadius:9,background:"#090f17",color:"var(--apivoy-text)",padding:"10px 11px",outline:"none"},secretRow:{display:"grid",gridTemplateColumns:"1fr auto",gap:7},textarea:{width:"100%",minHeight:100,resize:"vertical",border:"1px solid var(--apivoy-border)",borderRadius:9,background:"#090f17",color:"var(--apivoy-text)",padding:11,lineHeight:1.6},context:{width:"100%",minHeight:120,resize:"vertical",border:"1px solid var(--apivoy-border)",borderRadius:9,background:"#090f17",color:"#b8cada",padding:11,fontFamily:"var(--apivoy-mono)",fontSize:11},primary:{width:"100%",border:0,borderRadius:9,background:"var(--apivoy-panel)",color:"white",fontWeight:750,padding:"10px 14px",cursor:"pointer"},secondary:{border:"1px solid rgba(179,88,255,.36)",borderRadius:8,background:"rgba(179,88,255,.1)",color:"#e2c5ff",padding:"8px 11px",cursor:"pointer"},ghost:{border:"1px solid var(--apivoy-border)",borderRadius:8,background:"transparent",color:"var(--apivoy-muted)",padding:"8px 11px",marginLeft:6,cursor:"pointer"},safety:{marginTop:13,padding:"10px 11px",borderRadius:9,background:"rgba(73,207,158,.07)",color:"#9ecbb9",fontSize:11,lineHeight:1.5},output:{marginTop:13,border:"1px solid var(--apivoy-border)",borderRadius:13,background:"#070c12",overflow:"hidden"},outputHeader:{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"11px 14px",borderBottom:"1px solid var(--apivoy-border)"},notice:{marginTop:13,borderLeft:"3px solid #b358ff",background:"rgba(179,88,255,.08)",padding:"10px 13px",fontSize:12}};
