import { useEffect, useState } from "react";
import {
  getAiEndpoint,
  getAiModel,
  getAiSecretRef,
  setAiEndpoint,
  setAiModel,
  setAiSecretRef,
  subscribePreferences,
} from "./userPreferences";
import { Button, InlineAlert, StatusBadge, Textarea, TextInput } from "./Components";

export type AiTask="generate_request"|"explain_response"|"generate_assertions"|"generate_documentation";
export interface AiAssistRequest { endpoint:string; model:string; secretRef:string; task:AiTask; input:string; context?:string }
export interface AiAssistResponse { content:string; model:string }
export interface AiWorkbenchProps { onAssist:(request:AiAssistRequest)=>Promise<AiAssistResponse>; onPutSecret:(name:string,value:string)=>Promise<void> }

const tasks:Array<{id:AiTask;label:string;description:string}>=[{id:"generate_request",label:"生成请求",description:"从自然语言生成可编辑的 HTTP 请求"},{id:"explain_response",label:"解释响应",description:"定位状态、字段与潜在错误"},{id:"generate_assertions",label:"生成断言",description:"产出稳定的回归检查"},{id:"generate_documentation",label:"生成文档",description:"整理接口说明与示例"}];

export function AiWorkbench({onAssist,onPutSecret}:AiWorkbenchProps){
  const [endpoint,setEndpoint]=useState(getAiEndpoint);const [model,setModel]=useState(getAiModel);const [secretRef,setSecretRef]=useState(getAiSecretRef);const [secret,setSecret]=useState("");const [task,setTask]=useState<AiTask>("generate_request");const [input,setInput]=useState("");const [context,setContext]=useState("");const [output,setOutput]=useState("");const [message,setMessage]=useState("");const [loading,setLoading]=useState(false);
  useEffect(()=>subscribePreferences((keys)=>{if(keys.length===0||keys.some((key)=>key==="aiEndpoint"||key==="aiModel"||key==="aiSecretRef")){setEndpoint(getAiEndpoint());setModel(getAiModel());setSecretRef(getAiSecretRef());}}),[]);
  async function saveKey(){if(!secret.trim())return;try{await onPutSecret(secretRef,secret);setSecret("");setMessage(`密钥已安全保存为 ${secretRef}`);}catch(error){setMessage(error instanceof Error?error.message:String(error));}}
  async function run(){setLoading(true);setMessage("");try{setAiEndpoint(endpoint);setAiModel(model);setAiSecretRef(secretRef);const result=await onAssist({endpoint,model,secretRef,task,input,context:context||undefined});setOutput(result.content);setMessage(`由 ${result.model} 生成 · 请在应用前检查`);}catch(error){setMessage(error instanceof Error?error.message:String(error));}finally{setLoading(false);}}
  function applyRequest(){try{const cleaned=output.replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/,"");const value=JSON.parse(cleaned) as Record<string,unknown>;const headers=Array.isArray(value.headers)?value.headers:[];const request={name:String(value.name??"AI generated request"),method:String(value.method??"GET").toUpperCase(),url:String(value.url??""),headers,body:value.body==null?undefined:String(value.body),timeoutMs:30000,variables:typeof value.variables==="object"&&value.variables?value.variables:{},assertions:[],auth:null,followRedirects:true,retryMax:0,retryBackoffMs:250,proxy:null,tlsVerify:true};window.dispatchEvent(new CustomEvent("apivoy-open-request",{detail:{protocolId:"http",request,aiAssertions:typeof value.assertions==="string"?value.assertions:""}}));setMessage("已应用到 HTTP 工作台，发送前请检查 URL、Headers 与 Body");}catch(error){setMessage(`无法应用：${error instanceof Error?error.message:String(error)}`);}}
  return <section className="ai-workbench"><header className="ai-header"><div><small>LOCAL-FIRST AI COPILOT</small><h2>AI 辅助</h2><p>自带模型与密钥。上下文只会发送到你配置的提供商，生成结果永远先预览、后应用。</p></div><StatusBadge tone="info">BYOK · EXPLICIT</StatusBadge></header><div className="ai-tasks">{tasks.map(item=><button key={item.id} className={task===item.id?"is-active":undefined} aria-pressed={task===item.id} onClick={()=>setTask(item.id)}><b>{item.label}</b><span>{item.description}</span></button>)}</div><div className="ai-columns"><div className="ai-panel"><h3>模型连接</h3><label className="ai-field">OPENAI-COMPATIBLE ENDPOINT<TextInput value={endpoint} onChange={event=>{setEndpoint(event.target.value);setAiEndpoint(event.target.value);}} /></label><label className="ai-field">MODEL<TextInput value={model} onChange={event=>{setModel(event.target.value);setAiModel(event.target.value);}} /></label><label className="ai-field">SECRET REF<TextInput value={secretRef} onChange={event=>{setSecretRef(event.target.value);setAiSecretRef(event.target.value);}} /></label><div className="ai-secret-row"><TextInput type="password" placeholder="API Key（不会写入项目）" value={secret} onChange={event=>setSecret(event.target.value)} /><Button disabled={!secret.trim()} onClick={()=>void saveKey()}>存入密钥</Button></div><InlineAlert tone="success">远程地址强制 HTTPS；本机 Ollama/兼容服务可使用 HTTP localhost。</InlineAlert></div><div className="ai-panel"><h3>任务上下文</h3><label className="ai-field">INSTRUCTION<Textarea value={input} onChange={event=>setInput(event.target.value)} placeholder="例如：创建一个带分页参数的用户列表请求…" /></label><label className="ai-field">OPTIONAL CONTEXT<Textarea className="ai-context" value={context} onChange={event=>setContext(event.target.value)} placeholder="粘贴请求、响应或 Schema；请勿包含明文密钥" /></label><Button className="ai-generate" variant="primary" loading={loading} disabled={!input.trim()||!endpoint.trim()||!model.trim()} onClick={()=>void run()}>生成预览</Button></div></div><div className="ai-output"><div className="ai-output-header"><h3>生成结果</h3><div>{task==="generate_request"&&output&&<Button onClick={applyRequest}>应用到 HTTP</Button>}<Button variant="ghost" icon="copy" disabled={!output} onClick={()=>void navigator.clipboard.writeText(output)}>复制</Button></div></div><pre>{output||"生成结果会显示在这里。ApiVoy 不会自动执行或保存 AI 生成的请求。"}</pre></div>{message&&<InlineAlert title="AI 状态">{message}</InlineAlert>}</section>;
}
