import { useEffect,useState } from "react";
import { VirtualList } from "./VirtualList";
import { Button, InlineAlert, StatusBadge, TextInput } from "./Components";

export interface CaptureStatus { running:boolean; bind?:string; exchangeCount:number }
export interface CapturedExchange { id:string;method:string;url:string;status?:number;requestHeaders:Array<[string,string]>;responseHeaders:Array<[string,string]>;requestBodyPreview:string;responseBodyPreview:string;startedAt:string;durationMs:number;tunnel:boolean;error?:string }
export interface CaptureWorkbenchProps { onStatus:()=>Promise<CaptureStatus>;onStart:(bind:string)=>Promise<CaptureStatus>;onStop:()=>Promise<CaptureStatus>;onList:()=>Promise<CapturedExchange[]>;onClear:()=>Promise<void> }

export function CaptureWorkbench({onStatus,onStart,onStop,onList,onClear}:CaptureWorkbenchProps){const [status,setStatus]=useState<CaptureStatus>({running:false,exchangeCount:0});const [bind,setBind]=useState("127.0.0.1:39219");const [items,setItems]=useState<CapturedExchange[]>([]);const [selected,setSelected]=useState<CapturedExchange|null>(null);const [message,setMessage]=useState("");
  async function refresh(){try{const[nextStatus,nextItems]=await Promise.all([onStatus(),onList()]);setStatus(nextStatus);setItems(nextItems);if(selected)setSelected(nextItems.find(item=>item.id===selected.id)??null);}catch(error){setMessage(error instanceof Error?error.message:String(error));}}
  useEffect(()=>{void refresh();const timer=setInterval(()=>void refresh(),2000);return()=>clearInterval(timer);},[]);
  async function toggle(){try{setStatus(status.running?await onStop():await onStart(bind));await refresh();setMessage(status.running?"抓包代理已停止":"抓包代理已启动，请将应用代理指向下方地址");}catch(error){setMessage(error instanceof Error?error.message:String(error));}}
  async function clear(){await onClear();setItems([]);setSelected(null);setStatus(await onStatus());}
  function apply(item:CapturedExchange){if(item.tunnel)return;const headers=item.requestHeaders.filter(([name])=>!["host","content-length","proxy-connection","connection"].includes(name.toLowerCase()));window.dispatchEvent(new CustomEvent("apivoy-open-request",{detail:{protocolId:"http",request:{name:`Captured ${item.method}`,method:item.method,url:item.url,headers,body:item.requestBodyPreview||undefined,timeoutMs:30000,variables:{},assertions:[],auth:null,followRedirects:true,retryMax:0,retryBackoffMs:250,proxy:null,tlsVerify:true}}}));setMessage("已复制到 HTTP 工作台，敏感 Header 请在发送前检查并改用 secret_ref");}
  return <section className="capture-workbench"><header className="capture-header"><div><small>EXPLICIT TRAFFIC CAPTURE</small><h2>代理抓包</h2><p>HTTP 请求与响应可检查；HTTPS 保持端到端加密，仅记录 CONNECT 目标和耗时，不静默安装根证书。</p></div><StatusBadge tone={status.running?"warning":"neutral"}>{status.running?"CAPTURING":"STOPPED"}</StatusBadge></header><div className="capture-control"><div><small>PROXY ADDRESS</small><TextInput value={status.bind??bind} disabled={status.running} onChange={event=>setBind(event.target.value)} /></div><div><small>CONFIGURE YOUR APP</small><code>HTTP_PROXY=http://{status.bind??bind}</code></div><div className="capture-control-actions"><Button variant={status.running?"danger":"primary"} onClick={()=>void toggle()}>{status.running?"停止抓包":"开始抓包"}</Button><Button variant="ghost" onClick={()=>void clear()}>清空</Button></div></div><div className="capture-columns"><div className="capture-list"><div className="capture-list-header"><b>会话流</b><span>{items.length} / 500</span></div>{items.length===0&&<div className="capture-blank">启动代理并在目标应用中配置 HTTP 代理后，流量会出现在这里。</div>}<VirtualList items={items.slice().reverse()} itemHeight={58} height={Math.min(620, Math.max(120, items.length * 58))} ariaLabel="抓包会话流" getKey={(item) => item.id} renderItem={(item) => <button className={`capture-row${selected?.id===item.id?" is-active":""}`} onClick={()=>setSelected(item)}><span className={item.tunnel?"is-tunnel":undefined}>{item.method}</span><span><b>{item.url}</b><small>{new Date(item.startedAt).toLocaleTimeString()} · {item.durationMs} ms</small></span><code className={item.status&&item.status>=400?"is-danger":"is-success"}>{item.status??"—"}</code></button>} /></div><div className="capture-detail">{!selected?<div className="capture-empty-detail">选择一条会话查看 Headers 与正文预览</div>:<><div className="capture-detail-header"><div><small>{selected.tunnel?"ENCRYPTED TUNNEL":"CAPTURED EXCHANGE"}</small><h3>{selected.method} {selected.url}</h3></div>{!selected.tunnel&&<Button onClick={()=>apply(selected)}>生成 HTTP 请求</Button>}</div>{selected.error&&<InlineAlert tone="danger">{selected.error}</InlineAlert>}<Detail title="Request headers" headers={selected.requestHeaders} body={selected.requestBodyPreview}/><Detail title="Response headers" headers={selected.responseHeaders} body={selected.responseBodyPreview}/>{selected.tunnel&&<InlineAlert title="HTTPS 正文未解密">若需要调试 API 内容，请直接在 ApiVoy 请求工作台发送，或由组织显式部署受控 MITM 证书方案。</InlineAlert>}</>}</div></div>{message&&<InlineAlert title="抓包状态">{message}</InlineAlert>}</section>}
function Detail({title,headers,body}:{title:string;headers:Array<[string,string]>;body:string}){return <div className="capture-block"><h4>{title}</h4><div className="capture-headers">{headers.map(([name,value],index)=><div key={`${name}-${index}`}><b>{name}</b><span>{value}</span></div>)}</div>{body&&<pre>{body}</pre>}</div>}
