import { useEffect, useState, type CSSProperties } from "react";
import type { RequestEnvelope } from "@apivoy/request-model";
import { useQuery } from "@tanstack/react-query";

type Job = { id: string; name: string; intervalSeconds: number; nextRunAt: string; enabled: boolean; lastExecutionId?: string | null };
type Execution = { id: string; source: string; success: boolean; startedAt: string; error?: string | null; summary?: { durationMs: number; protocolId: string; status?: number | null } | null };

function defaultRequest(): RequestEnvelope {
  return { id: crypto.randomUUID(), protocolId: "http", name: "Gateway health check", target: "https://example.com", environmentRef: null, authRef: null, timeoutMs: 30000, retryPolicy: { max_retries: 0, backoff_ms: 0 }, proxy: null, tls: { verify: true, client_cert_ref: null }, metadata: {}, payload: { type: "http", method: "GET", headers: [], body: null, multipart: [], followRedirects: true }, preScripts: [], postScripts: [], assertions: [], variables: {}, createdAt: new Date().toISOString() };
}

export function GatewayWorkbench() {
  const [baseUrl, setBaseUrl] = useState(() => sessionStorage.getItem("apivoy:gateway-url") ?? `${location.origin}/gateway`);
  const [apiKey, setApiKey] = useState(() => sessionStorage.getItem("apivoy:gateway-key") ?? "");
  const [requestText, setRequestText] = useState(() => JSON.stringify(defaultRequest(), null, 2));
  const [jobName, setJobName] = useState("Scheduled gateway check");
  const [intervalSeconds, setIntervalSeconds] = useState(300);
  const [output, setOutput] = useState("配置 Gateway API Key 后可远程执行、创建定时任务或刷新历史。\nAPI Key 仅保留在当前浏览器会话中。");
  const [busy, setBusy] = useState(false);
  const jobsQuery = useQuery({ queryKey: ["gateway", baseUrl, apiKey, "jobs"], queryFn: () => call<Job[]>("/v1/jobs"), enabled: false, initialData: [] });
  const executionsQuery = useQuery({ queryKey: ["gateway", baseUrl, apiKey, "executions"], queryFn: () => call<Execution[]>("/v1/executions"), enabled: false, initialData: [] });
  const jobs = jobsQuery.data;
  const executions = executionsQuery.data;

  useEffect(() => { sessionStorage.setItem("apivoy:gateway-url", baseUrl); sessionStorage.setItem("apivoy:gateway-key", apiKey); }, [baseUrl, apiKey]);
  async function call<T>(path: string, init?: RequestInit): Promise<T> { const response = await fetch(`${baseUrl.replace(/\/$/, "")}${path}`, { ...init, headers: { "Content-Type": "application/json", Authorization: `Bearer ${apiKey}`, ...init?.headers } }); const body = response.status === 204 ? null : await response.json(); if (!response.ok) throw new Error((body as { error?: string } | null)?.error ?? `Gateway HTTP ${response.status}`); return body as T; }
  function request() { return JSON.parse(requestText) as RequestEnvelope; }
  async function run(source: "remote" | "ci") { setBusy(true); try { const body = source === "ci" ? { request: request(), failOnAssertion: true } : request(); const result = await call<unknown>(source === "ci" ? "/v1/runner/execute" : "/v1/executions", { method: "POST", body: JSON.stringify(body) }); setOutput(JSON.stringify(result, null, 2)); await refresh(); } catch (error) { setOutput(error instanceof Error ? error.message : String(error)); } finally { setBusy(false); } }
  async function schedule() { setBusy(true); try { const result = await call<Job>("/v1/jobs", { method: "POST", body: JSON.stringify({ name: jobName, intervalSeconds, enabled: true, request: request() }) }); setOutput(`已创建定时任务 ${result.id}`); await refresh(); } catch (error) { setOutput(error instanceof Error ? error.message : String(error)); } finally { setBusy(false); } }
  async function refresh() { if (!apiKey) return; try { const results = await Promise.all([jobsQuery.refetch(), executionsQuery.refetch()]); const error = results.find(result => result.error)?.error; if (error) throw error; } catch (error) { setOutput(error instanceof Error ? error.message : String(error)); } }
  async function remove(id: string) { await call(`/v1/jobs/${id}`, { method: "DELETE" }); await refresh(); }

  return <section style={styles.root}><header style={styles.header}><div><small style={styles.eyebrow}>REMOTE · SCHEDULED · CI</small><h2 style={styles.title}>云协议网关</h2><p style={styles.copy}>复用 ApiVoy 全协议内核，在受控服务中执行远程请求、周期任务与 CI 检查。</p></div><span style={styles.badge}>BEARER AUTH</span></header><div style={styles.credentials}><label style={styles.label}>GATEWAY URL<input style={styles.input} value={baseUrl} onChange={event=>setBaseUrl(event.target.value)} /></label><label style={styles.label}>SESSION API KEY<input style={styles.input} type="password" value={apiKey} onChange={event=>setApiKey(event.target.value)} placeholder="至少 24 位" /></label><button style={styles.secondary} disabled={!apiKey||busy} onClick={()=>void refresh()}>刷新状态</button></div><div style={styles.grid}><div style={styles.panel}><div style={styles.panelTitle}><h3>RequestEnvelope</h3><span>JSON</span></div><textarea style={styles.editor} value={requestText} onChange={event=>setRequestText(event.target.value)} spellCheck={false}/><div style={styles.actions}><button style={styles.primary} disabled={!apiKey||busy} onClick={()=>void run("remote")}>远程执行</button><button style={styles.secondary} disabled={!apiKey||busy} onClick={()=>void run("ci")}>CI Runner</button></div></div><div style={styles.panel}><div style={styles.panelTitle}><h3>定时任务</h3><span>{jobs.length} JOBS</span></div><div style={styles.schedule}><input style={styles.input} value={jobName} onChange={event=>setJobName(event.target.value)} /><label style={styles.label}>INTERVAL SECONDS<input style={styles.input} type="number" min={10} value={intervalSeconds} onChange={event=>setIntervalSeconds(Math.max(10,+event.target.value))}/></label><button style={styles.primary} disabled={!apiKey||busy} onClick={()=>void schedule()}>创建任务</button></div><div style={styles.list}>{jobs.map(job=><div style={styles.item} key={job.id}><div><b>{job.name}</b><small>每 {job.intervalSeconds}s · 下次 {new Date(job.nextRunAt).toLocaleString()}</small></div><button style={styles.danger} onClick={()=>void remove(job.id)}>删除</button></div>)}{jobs.length===0&&<div style={styles.empty}>暂无定时任务</div>}</div></div></div><div style={styles.results}><div style={styles.panelTitle}><h3>网关输出与脱敏历史</h3><span>{executions.length} RUNS</span></div><div style={styles.history}>{executions.slice(0,8).map(item=><div style={styles.run} key={item.id}><span style={{...styles.dot,background:item.success?"var(--apivoy-success)":"var(--apivoy-danger)"}}/><b>{item.source}</b><code>{item.summary?.protocolId??"failed"}</code><span>{item.summary?.durationMs??0} ms</span></div>)}</div><pre style={styles.output}>{output}</pre></div></section>;
}

const styles: Record<string,CSSProperties>={root:{display:"grid",gap:16},header:{display:"flex",justifyContent:"space-between",alignItems:"start",padding:"22px 24px",border:"1px solid var(--apivoy-border)",borderRadius:16,background:"var(--apivoy-panel)"},eyebrow:{color:"var(--apivoy-accent)",fontWeight:800,letterSpacing:1.5},title:{margin:"6px 0",fontSize:26},copy:{margin:0,color:"var(--apivoy-muted)"},badge:{padding:"7px 10px",border:"1px solid rgba(62,207,142,.35)",borderRadius:999,color:"var(--apivoy-success)",fontSize:11,fontWeight:800},credentials:{display:"grid",gridTemplateColumns:"1fr 1fr auto",gap:12,alignItems:"end",padding:16,border:"1px solid var(--apivoy-border)",borderRadius:14,background:"var(--apivoy-bg-elevated)"},label:{display:"grid",gap:6,fontSize:10,fontWeight:750,color:"var(--apivoy-muted)",letterSpacing:.8},input:{width:"100%",padding:"10px 11px",border:"1px solid var(--apivoy-border)",borderRadius:8,background:"#090f16",color:"var(--apivoy-text)"},grid:{display:"grid",gridTemplateColumns:"minmax(0,1.25fr) minmax(300px,.75fr)",gap:16},panel:{padding:16,border:"1px solid var(--apivoy-border)",borderRadius:14,background:"rgba(13,20,29,.82)"},panelTitle:{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:12},editor:{width:"100%",minHeight:340,padding:14,border:"1px solid var(--apivoy-border)",borderRadius:10,background:"#070c12",color:"#d7e9f8",fontFamily:"var(--apivoy-mono)",fontSize:12,resize:"vertical"},actions:{display:"flex",gap:8,marginTop:12},primary:{padding:"10px 14px",border:0,borderRadius:8,background:"var(--apivoy-panel)",color:"white",fontWeight:750,cursor:"pointer"},secondary:{padding:"10px 14px",border:"1px solid var(--apivoy-border)",borderRadius:8,background:"#111a25",color:"var(--apivoy-text)",cursor:"pointer"},danger:{padding:"6px 9px",border:"1px solid rgba(240,113,120,.3)",borderRadius:7,background:"rgba(240,113,120,.08)",color:"var(--apivoy-danger)",cursor:"pointer"},schedule:{display:"grid",gap:10},list:{display:"grid",gap:7,marginTop:14},item:{display:"flex",justifyContent:"space-between",alignItems:"center",padding:10,border:"1px solid var(--apivoy-border)",borderRadius:9},empty:{padding:25,textAlign:"center",color:"var(--apivoy-muted)"},results:{padding:16,border:"1px solid var(--apivoy-border)",borderRadius:14,background:"rgba(13,20,29,.82)"},history:{display:"flex",flexWrap:"wrap",gap:7,marginBottom:10},run:{display:"flex",alignItems:"center",gap:7,padding:"6px 9px",border:"1px solid var(--apivoy-border)",borderRadius:8,fontSize:11},dot:{width:6,height:6,borderRadius:99},output:{maxHeight:360,overflow:"auto",padding:14,borderRadius:10,background:"#060a0f",color:"#bcd4e8",whiteSpace:"pre-wrap",fontSize:12}};
