import { useEffect, useState, type CSSProperties } from "react";
import type { HttpRunResult, HttpSendHooks } from "./HttpWorkbench";
import { ProtocolCodeGenerator } from "./ProtocolCodeGenerator";
import { readWorkbenchDraft, useAutosaveDraft } from "./draftRecovery";

export interface GrpcWorkbenchRequest { name: string; target: string; service: string; method: string; messageBase64: string; messageJson?: string | null; descriptorSetBase64?: string | null; mode: "unary" | "server_streaming" | "client_streaming" | "bidi_streaming"; metadata: Array<[string, string]>; timeoutMs: number }
export interface GrpcWorkbenchProps { onSend: (request: GrpcWorkbenchRequest, hooks?: HttpSendHooks) => Promise<HttpRunResult>; onCancel: (executionId: string) => Promise<void>; onSave?: (request: GrpcWorkbenchRequest) => Promise<void>; externalRequest?: GrpcWorkbenchRequest | null }

export function GrpcWorkbench({ onSend, onCancel, onSave, externalRequest }: GrpcWorkbenchProps) {
  const [target, setTarget] = useState("http://127.0.0.1:50051"); const [service, setService] = useState("package.Service"); const [method, setMethod] = useState("Method"); const [mode, setMode] = useState<GrpcWorkbenchRequest["mode"]>("unary"); const [messageMode, setMessageMode] = useState<"json" | "base64">("base64"); const [message, setMessage] = useState(""); const [descriptorSetBase64, setDescriptorSetBase64] = useState(""); const [metadataText, setMetadataText] = useState(""); const [timeoutMs, setTimeoutMs] = useState(30000); const [output, setOutput] = useState("尚未调用"); const [runningId, setRunningId] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  useEffect(() => { const apply = (value: GrpcWorkbenchRequest) => { setTarget(value.target); setService(value.service); setMethod(value.method); setMode(value.mode); const json = value.messageJson; setMessageMode(json != null ? "json" : "base64"); setMessage(json ?? value.messageBase64); setDescriptorSetBase64(value.descriptorSetBase64 ?? ""); setMetadataText(value.metadata.map(([name, item]) => `${name}: ${item}`).join("\n")); setTimeoutMs(value.timeoutMs); }; if (externalRequest) apply(externalRequest); else { const draft = readWorkbenchDraft<GrpcWorkbenchRequest>("grpc"); if (draft) apply(draft); } const listener = (event: Event) => { const envelope = (event as CustomEvent).detail; const payload = envelope?.payload; if (payload?.type === "grpc") apply({ name: envelope.name, target: envelope.target, service: payload.service, method: payload.method, messageBase64: payload.messageBase64, messageJson: payload.messageJson, descriptorSetBase64: payload.descriptorSetBase64, mode: payload.mode, metadata: payload.metadata, timeoutMs: envelope.timeoutMs }); }; window.addEventListener("apivoy-open-request", listener); return () => window.removeEventListener("apivoy-open-request", listener); }, [externalRequest]);
  async function loadDescriptor(file: File | null) { if (!file) return; const bytes = new Uint8Array(await file.arrayBuffer()); let binary = ""; for (let offset = 0; offset < bytes.length; offset += 0x8000) binary += String.fromCharCode(...bytes.subarray(offset, offset + 0x8000)); setDescriptorSetBase64(btoa(binary)); }
  const request = (): GrpcWorkbenchRequest => ({ name: `${service}/${method}`, target, service, method, messageBase64: messageMode === "base64" ? message : "", messageJson: messageMode === "json" ? message : null, descriptorSetBase64: descriptorSetBase64 || null, mode, metadata: metadataText.split("\n").filter(Boolean).map((line): [string, string] => { const index = line.indexOf(":"); return index < 0 ? [line.trim(), ""] : [line.slice(0, index).trim(), line.slice(index + 1).trim()]; }), timeoutMs });
  useAutosaveDraft("grpc", request);
  async function send() { setBusy(true); setOutput("正在调用 gRPC…"); try { const result = await onSend(request(), { onStarted: setRunningId, onChunk: (chunk) => setOutput((current) => current === "正在调用 gRPC…" ? chunk : `${current}\n${chunk}`) }); if (result.error) setOutput((current) => `${current}\n调用失败：${result.error}`); else if (!result.preview) setOutput((current) => `${current}\n完成，收到 ${result.summary.bytesReceived} protobuf bytes`); } catch (error) { setOutput(error instanceof Error ? error.message : String(error)); } finally { setBusy(false); setRunningId(null); } }
  return <section style={styles.root}><div style={styles.title}><div><small style={styles.eyebrow}>HTTP/2 RPC</small><h2 style={styles.h2}>gRPC</h2></div><select style={styles.select} value={mode} onChange={(event) => setMode(event.target.value as typeof mode)}><option value="unary">Unary</option><option value="server_streaming">Server Streaming</option><option value="client_streaming">Client Streaming</option><option value="bidi_streaming">Bidirectional Streaming</option></select></div>
    <div style={styles.row}><input style={styles.target} value={target} onChange={(event) => setTarget(event.target.value)} placeholder="http://host:50051"/><button style={styles.send} disabled={busy} onClick={() => void send()}>调用</button>{onSave && <button style={styles.secondary} disabled={busy} onClick={() => void onSave(request())}>保存</button>}{runningId && <button style={styles.cancel} onClick={() => void onCancel(runningId)}>取消</button>}</div>
    <div style={styles.method}><input value={service} onChange={(event) => setService(event.target.value)} placeholder="package.Service"/><span>/</span><input value={method} onChange={(event) => setMethod(event.target.value)} placeholder="Method"/><label>超时 ms<input type="number" min={1} value={timeoutMs} onChange={(event) => setTimeoutMs(+event.target.value)}/></label></div>
    <div style={styles.options}><label>FileDescriptorSet (.bin/.pb)<input type="file" onChange={(event) => void loadDescriptor(event.target.files?.[0] ?? null)}/></label><span>{descriptorSetBase64 ? "Descriptor 已加载" : "未加载时将自动使用 Server Reflection"}</span><label>消息格式<select value={messageMode} onChange={(event) => setMessageMode(event.target.value as typeof messageMode)}><option value="base64">Protobuf Base64</option><option value="json">JSON（Descriptor / Reflection）</option></select></label></div>
    <label style={styles.label}>请求消息<textarea style={styles.message} value={message} onChange={(event) => setMessage(event.target.value)} placeholder={messageMode === "json" ? '{"name":"ApiVoy"}' : "空消息留空；protobuf bytes 使用 Base64"}/></label><label style={styles.label}>Metadata（每行 Name: Value）<textarea style={styles.metadata} value={metadataText} onChange={(event) => setMetadataText(event.target.value)}/></label><ProtocolCodeGenerator input={{ protocol: "grpc", request: request() }} /><pre style={styles.output}>{output}</pre>
  </section>;
}

const styles: Record<string, CSSProperties> = { root: { marginTop: 22, padding: 18, border: "1px solid var(--apivoy-border)", borderRadius: 14, background: "linear-gradient(145deg,#10171b,#091016)" }, title: { display: "flex", justifyContent: "space-between" }, eyebrow: { color: "#69d39a", letterSpacing: 1.4 }, h2: { margin: "3px 0 14px", fontSize: 18 }, select: { alignSelf: "center", background: "#101a20", color: "var(--apivoy-text)", border: "1px solid var(--apivoy-border)", borderRadius: 8, padding: 8 }, row: { display: "flex", gap: 8 }, target: { flex: 1, background: "#071014", color: "var(--apivoy-text)", border: "1px solid var(--apivoy-border)", borderRadius: 8, padding: 10 }, send: { border: 0, borderRadius: 8, background: "#60d092", color: "#06170d", fontWeight: 700, padding: "0 18px" }, secondary: { border: "1px solid var(--apivoy-border)", borderRadius: 8, background: "#112019", color: "#bde8cd", padding: "0 12px" }, cancel: { border: "1px solid #71434a", borderRadius: 8, background: "#2b171b", color: "#ff9ca8" }, method: { display: "flex", alignItems: "center", gap: 7, marginTop: 10, color: "var(--apivoy-muted)", fontSize: 11 }, options: { display: "flex", gap: 12, alignItems: "center", marginTop: 10, color: "var(--apivoy-muted)", fontSize: 11 }, label: { display: "block", marginTop: 10, color: "var(--apivoy-muted)", fontSize: 11 }, message: { boxSizing: "border-box", width: "100%", minHeight: 100, marginTop: 6, background: "#070d11", color: "#c8e8d7", border: "1px solid var(--apivoy-border)", borderRadius: 8, padding: 10, fontFamily: "monospace" }, metadata: { boxSizing: "border-box", width: "100%", minHeight: 55, marginTop: 6, background: "#070d11", color: "#c8e8d7", border: "1px solid var(--apivoy-border)", borderRadius: 8, padding: 10 }, output: { minHeight: 80, maxHeight: 320, overflow: "auto", whiteSpace: "pre-wrap", background: "#060b0e", border: "1px solid var(--apivoy-border)", borderRadius: 8, padding: 10, color: "#bfe4d0" } };
