import { useEffect, useState, type CSSProperties } from "react";
import type { HttpRunResult, HttpSendHooks } from "./HttpWorkbench";

export interface MqttWorkbenchRequest {
  name: string; target: string; mode: "publish" | "subscribe"; clientId: string;
  username: string; passwordRef: string; cleanSession: boolean; keepAliveSeconds: number;
  topic: string; payload: string; encoding: "text" | "base64"; qos: 0 | 1 | 2;
  retain: boolean; receiveLimit: number; caPemRef: string; serverName: string; timeoutMs: number;
}
export interface MqttWorkbenchProps {
  onSend: (request: MqttWorkbenchRequest, hooks?: HttpSendHooks) => Promise<HttpRunResult>;
  onSave?: (request: MqttWorkbenchRequest) => Promise<void>;
  onCancel?: (executionId: string) => Promise<void>;
}

export function MqttWorkbench({ onSend, onSave, onCancel }: MqttWorkbenchProps) {
  const [name,setName]=useState("MQTT request"), [target,setTarget]=useState("mqtt://127.0.0.1:1883");
  const [mode,setMode]=useState<"publish"|"subscribe">("publish"), [clientId,setClientId]=useState(`apivoy-${crypto.randomUUID().slice(0,8)}`);
  const [username,setUsername]=useState(""), [passwordRef,setPasswordRef]=useState(""), [cleanSession,setCleanSession]=useState(true), [keepAliveSeconds,setKeepAliveSeconds]=useState(30);
  const [topic,setTopic]=useState("apivoy/demo"), [payload,setPayload]=useState('{"hello":"mqtt"}'), [encoding,setEncoding]=useState<"text"|"base64">("text");
  const [qos,setQos]=useState<0|1|2>(0), [retain,setRetain]=useState(false), [receiveLimit,setReceiveLimit]=useState(1);
  const [caPemRef,setCaPemRef]=useState(""), [serverName,setServerName]=useState("");
  const [result,setResult]=useState<HttpRunResult|null>(null), [message,setMessage]=useState(""), [loading,setLoading]=useState(false), [executionId,setExecutionId]=useState<string|null>(null);

  useEffect(()=>{const listener=(event:Event)=>{const envelope=(event as CustomEvent).detail;if(envelope?.protocolId!=="mqtt"||envelope.payload?.type!=="raw")return;const raw=envelope.payload.value??envelope.payload;setName(envelope.name);setTarget(envelope.target);setMode(raw.mode??"publish");setClientId(raw.clientId??"");setUsername(raw.username??"");setPasswordRef(raw.passwordRef??"");setCleanSession(raw.cleanSession??true);setKeepAliveSeconds(raw.keepAliveSeconds??30);setTopic(raw.topic??"");setPayload(raw.payload??"");setEncoding(raw.encoding??"text");setQos(raw.qos??0);setRetain(raw.retain??false);setReceiveLimit(raw.receiveLimit??1);setCaPemRef(raw.caPemRef??"");setServerName(raw.serverName??"")};window.addEventListener("apivoy-open-request",listener);return()=>window.removeEventListener("apivoy-open-request",listener)},[]);
  const build=():MqttWorkbenchRequest=>({name,target,mode,clientId,username,passwordRef,cleanSession,keepAliveSeconds,topic,payload,encoding,qos,retain,receiveLimit,caPemRef,serverName,timeoutMs:30000});
  async function send(){setLoading(true);setResult(null);setMessage("");try{setResult(await onSend(build(),{onStarted:setExecutionId,onChunk:()=>{}}))}catch(error){setMessage(error instanceof Error?error.message:String(error))}finally{setLoading(false);setExecutionId(null)}}
  async function save(){if(!onSave)return;try{await onSave(build());setMessage("已保存到集合")}catch(error){setMessage(error instanceof Error?error.message:String(error))}}
  const tls=target.startsWith("mqtts://");
  return <section style={styles.root}>
    <header style={styles.header}><div><small style={styles.eyebrow}>MESSAGE BROKER</small><h2 style={styles.title}>MQTT Studio</h2><p style={styles.subtitle}>MQTT 3.1.1 · QoS 0/1/2 · MQTTS · Publish / Subscribe</p></div><div style={styles.segment}><button style={mode==="publish"?styles.active:styles.segmentButton} onClick={()=>setMode("publish")}>Publish</button><button style={mode==="subscribe"?styles.active:styles.segmentButton} onClick={()=>setMode("subscribe")}>Subscribe</button></div></header>
    <div style={styles.targetRow}><input style={styles.name} value={name} onChange={e=>setName(e.target.value)}/><input style={styles.target} value={target} onChange={e=>setTarget(e.target.value)}/><button style={styles.send} disabled={loading} onClick={()=>void send()}>{loading?"运行中…":mode==="publish"?"Publish":"Subscribe"}</button>{loading&&onCancel&&<button style={styles.cancel} onClick={()=>executionId&&void onCancel(executionId)}>取消</button>}</div>
    <div style={styles.grid}><div style={styles.card}>
      <div style={styles.fields}><Label text="CLIENT ID"><input style={styles.input} value={clientId} onChange={e=>setClientId(e.target.value)}/></Label><Label text="USERNAME"><input style={styles.input} value={username} onChange={e=>setUsername(e.target.value)}/></Label><Label text="PASSWORD SECRET REF"><input style={styles.input} value={passwordRef} onChange={e=>setPasswordRef(e.target.value)} placeholder="mqtt-password"/></Label></div>
      <div style={styles.fields}><Label text="TOPIC"><input style={styles.input} value={topic} onChange={e=>setTopic(e.target.value)}/></Label><Label text="QoS"><select style={styles.input} value={qos} onChange={e=>setQos(Number(e.target.value) as 0|1|2)}><option value={0}>0 · at most once</option><option value={1}>1 · at least once</option><option value={2}>2 · exactly once</option></select></Label>{mode==="subscribe"?<Label text="MESSAGE LIMIT"><input style={styles.input} type="number" min={1} value={receiveLimit} onChange={e=>setReceiveLimit(Math.max(1,Number(e.target.value)))}/></Label>:<Label text="ENCODING"><select style={styles.input} value={encoding} onChange={e=>setEncoding(e.target.value as "text"|"base64")}><option value="text">Text</option><option value="base64">Base64</option></select></Label>}</div>
      {mode==="publish"&&<Label text="MESSAGE"><textarea style={styles.editor} value={payload} onChange={e=>setPayload(e.target.value)}/></Label>}
      {tls&&<div style={styles.tls}><Label text="CA PEM SECRET REF"><input style={styles.input} value={caPemRef} onChange={e=>setCaPemRef(e.target.value)} placeholder="mqtt-ca-pem"/></Label><Label text="SERVER NAME / SNI"><input style={styles.input} value={serverName} onChange={e=>setServerName(e.target.value)} placeholder="broker.example.com"/></Label></div>}
      <div style={styles.options}><label><input type="checkbox" checked={cleanSession} onChange={e=>setCleanSession(e.target.checked)}/> Clean session</label>{mode==="publish"&&<label><input type="checkbox" checked={retain} onChange={e=>setRetain(e.target.checked)}/> Retain</label>}<label>Keep alive <input style={styles.number} type="number" min={0} max={65535} value={keepAliveSeconds} onChange={e=>setKeepAliveSeconds(Number(e.target.value))}/> s</label></div>
      {onSave&&<button style={styles.secondary} onClick={()=>void save()}>保存到集合</button>}
    </div><div style={styles.response}><div style={styles.responseHeader}><b>{mode==="publish"?"Publish acknowledgement":"Incoming messages"}</b>{result&&<span>{result.summary.durationMs} ms</span>}</div><pre style={styles.preview}>{result?.preview??(mode==="publish"?"发布确认会显示在这里":"订阅消息会实时追加到这里")}</pre></div></div>{message&&<div style={styles.notice}>{message}</div>}
  </section>;
}
function Label({text,children}:{text:string;children:React.ReactNode}){return <label style={styles.label}>{text}{children}</label>}
const styles:Record<string,CSSProperties>={root:{padding:22,border:"1px solid var(--apivoy-border)",borderRadius:18,background:"var(--apivoy-panel)"},header:{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:18},eyebrow:{fontSize:10,fontWeight:800,letterSpacing:2,color:"#a89cff"},title:{fontSize:27,margin:"5px 0 2px"},subtitle:{margin:0,color:"var(--apivoy-muted)",fontSize:12},segment:{display:"flex",padding:3,borderRadius:9,background:"#070b13"},segmentButton:{border:0,borderRadius:7,padding:"8px 13px",background:"transparent",color:"var(--apivoy-muted)"},active:{border:0,borderRadius:7,padding:"8px 13px",background:"rgba(115,97,255,.18)",color:"#ddd8ff"},targetRow:{display:"grid",gridTemplateColumns:"170px 1fr auto auto",gap:8,marginBottom:12},name:{border:"1px solid var(--apivoy-border)",borderRadius:8,padding:10,background:"#080d15",color:"var(--apivoy-text)"},target:{border:"1px solid var(--apivoy-border)",borderRadius:8,padding:10,background:"#080d15",color:"#d8d2ff",fontFamily:"var(--apivoy-mono)"},send:{border:0,borderRadius:8,padding:"10px 17px",background:"var(--apivoy-panel)",color:"white",fontWeight:800},cancel:{border:"1px solid #635b8f",borderRadius:8,background:"#18152c",color:"#d8d1ff"},grid:{display:"grid",gridTemplateColumns:"minmax(470px,1.1fr) minmax(350px,.9fr)",gap:12},card:{border:"1px solid var(--apivoy-border)",borderRadius:12,padding:14,background:"rgba(4,7,13,.5)"},fields:{display:"grid",gridTemplateColumns:"repeat(3,minmax(0,1fr))",gap:8},tls:{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,borderTop:"1px solid var(--apivoy-border)",paddingTop:10},label:{display:"grid",gap:6,color:"var(--apivoy-muted)",fontSize:10,fontWeight:750,marginBottom:10},input:{width:"100%",border:"1px solid var(--apivoy-border)",borderRadius:8,padding:9,background:"#070b12",color:"var(--apivoy-text)"},editor:{width:"100%",minHeight:190,resize:"vertical",border:"1px solid var(--apivoy-border)",borderRadius:9,padding:12,background:"#050810",color:"#d9d5ff",fontFamily:"var(--apivoy-mono)",lineHeight:1.55},options:{display:"flex",alignItems:"center",gap:18,color:"var(--apivoy-muted)",fontSize:11,margin:"2px 0 12px"},number:{width:64,border:"1px solid var(--apivoy-border)",borderRadius:6,background:"#080c14",color:"white",padding:5},secondary:{border:"1px solid rgba(115,97,255,.4)",borderRadius:8,background:"rgba(115,97,255,.1)",color:"#d7d1ff",padding:"9px 12px"},response:{border:"1px solid var(--apivoy-border)",borderRadius:12,background:"#05080e",overflow:"hidden"},responseHeader:{display:"flex",justifyContent:"space-between",padding:12,borderBottom:"1px solid var(--apivoy-border)"},preview:{minHeight:310,margin:0,padding:14,whiteSpace:"pre-wrap",overflow:"auto",color:"#bdc9e9"},notice:{marginTop:12,borderLeft:"3px solid #7866ff",padding:"10px 13px",background:"rgba(115,97,255,.09)"}};
