import { useEffect, useMemo, useState } from "react";
import { CodeEditor } from "./CodeEditor";
import { Icon } from "./Icons";
import { createScriptAsset, readScriptAssets, writeScriptAssets, type ScriptAsset, type ScriptLanguage } from "./scriptLibrary";
import { createScriptResource,listScriptResources,updateScriptResource } from "./agentResources";
export function ScriptLibraryWorkbench({ projectId }: { projectId: string }) {
  const [assets,setAssets]=useState<ScriptAsset[]>(()=>readScriptAssets(projectId)); const [query,setQuery]=useState(""); const [selectedId,setSelectedId]=useState<string>("");
  useEffect(()=>{const cached=readScriptAssets(projectId);setAssets(cached);setSelectedId((id)=>cached.some((item)=>item.id===id)?id:cached[0]?.id??"");listScriptResources(projectId).then((next)=>{setAssets(next);writeScriptAssets(projectId,next);setSelectedId((id)=>next.some((item)=>item.id===id)?id:next[0]?.id??"")}).catch(()=>{})},[projectId]);
  const selected=assets.find((item)=>item.id===selectedId); const filtered=useMemo(()=>assets.filter((item)=>item.name.toLowerCase().includes(query.toLowerCase())),[assets,query]);
  const commit=(next:ScriptAsset[])=>{setAssets(next);writeScriptAssets(projectId,next)}; const update=(patch:Partial<ScriptAsset>)=>{if(!selected)return;const changed={...selected,...patch,updatedAt:new Date().toISOString()};commit(assets.map((item)=>item.id===selected.id?changed:item));void updateScriptResource(changed).catch(()=>{})};
  const add=()=>{const draft=createScriptAsset(projectId);createScriptResource(draft).then((item)=>{commit([...assets,item]);setSelectedId(item.id)}).catch(()=>{commit([...assets,draft]);setSelectedId(draft.id)})};
  return <section className="script-library"><aside><header><div><strong>项目脚本库</strong><small>JavaScript / TypeScript</small></div><button className="ui-icon-button compact" type="button" aria-label="新建脚本" onClick={add}><Icon name="plus"/></button></header><input aria-label="搜索脚本" placeholder="搜索脚本" value={query} onChange={(event)=>setQuery(event.target.value)}/><div className="script-list">{filtered.map((item)=><button key={item.id} type="button" className={item.id===selectedId?"is-active":undefined} onClick={()=>setSelectedId(item.id)}><Icon name="code"/><span><strong>{item.name}</strong><small>{item.language}</small></span></button>)}</div></aside><main>{selected?<><header><input aria-label="脚本名称" value={selected.name} onChange={(event)=>update({name:event.target.value})}/><select aria-label="脚本语言" value={selected.language} onChange={(event)=>update({language:event.target.value as ScriptLanguage})}><option value="javascript">JavaScript</option><option value="typescript">TypeScript</option></select><button className="ui-button secondary" onClick={()=>{const copy={...selected,id:crypto.randomUUID(),name:`${selected.name} 副本`,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};commit([...assets,copy]);setSelectedId(copy.id)}}>复制</button><button className="ui-button danger" onClick={()=>{const next=assets.filter((item)=>item.id!==selected.id);commit(next);setSelectedId(next[0]?.id??"")}}>删除</button></header><CodeEditor value={selected.source} onChange={(source)=>update({source})} language={selected.language} height="100%"/></>:<div className="script-empty"><Icon name="code"/><strong>还没有项目脚本</strong><span>创建脚本后，可在请求的前置或后置操作中引用。</span><button className="ui-button primary" onClick={add}>新建脚本</button></div>}</main></section>;
}
