export type ScriptLanguage = "javascript" | "typescript";
export interface ScriptAsset { id: string; projectId: string; name: string; language: ScriptLanguage; source: string; createdAt: string; updatedAt: string }
export interface ScriptStep { id: string; enabled: boolean; sourceType: "asset" | "inline"; scriptId?: string; language: ScriptLanguage; source?: string }
const KEY = "apivoy-project-scripts-v1";
export function readScriptAssets(projectId: string): ScriptAsset[] { try { const value = JSON.parse(localStorage.getItem(KEY) ?? "[]") as ScriptAsset[]; return value.filter((item) => item.projectId === projectId); } catch { return []; } }
export function writeScriptAssets(projectId: string, assets: ScriptAsset[]) { const other = (() => { try { return (JSON.parse(localStorage.getItem(KEY) ?? "[]") as ScriptAsset[]).filter((item) => item.projectId !== projectId); } catch { return []; } })(); localStorage.setItem(KEY, JSON.stringify([...other,...assets])); window.dispatchEvent(new CustomEvent("apivoy-script-library-change",{detail:{projectId}})); }
export function createScriptAsset(projectId: string, name = "新建脚本", language: ScriptLanguage = "javascript"): ScriptAsset { const now = new Date().toISOString(); return { id: crypto.randomUUID(), projectId, name, language, source: language === "typescript" ? "const value: string = 'ApiVoy';\nconsole.log(value);" : "console.log('ApiVoy');", createdAt: now, updatedAt: now }; }
export function legacyScriptSteps(values?: string[]): ScriptStep[] { return (values ?? []).map((source) => ({ id: crypto.randomUUID(), enabled: true, sourceType: "inline", language: "javascript", source })); }
export function resolveScriptSteps(steps: ScriptStep[], assets: ScriptAsset[]): string[] { return steps.filter((step) => step.enabled).map((step) => step.sourceType === "asset" ? assets.find((asset) => asset.id === step.scriptId)?.source : step.source).filter((source): source is string => typeof source === "string" && !!source.trim()); }
