import { useEffect, useState } from "react";
import { Icon } from "./Icons";
import type { ScriptAsset } from "./scriptLibrary";
function readAssets():ScriptAsset[]{try{return JSON.parse(localStorage.getItem("apivoy-project-scripts-v1")??"[]") as ScriptAsset[]}catch{return[]}}
export function ScriptStepEditor({ assetIds,onAssetIdsChange,readOnly=false,phase }:{assetIds:string[];onAssetIdsChange:(ids:string[])=>void;readOnly?:boolean;phase:"pre"|"post"}) {
 const [assets,setAssets]=useState<ScriptAsset[]>(readAssets); const [selected,setSelected]=useState(""); const [drag,setDrag]=useState<number|null>(null);
 useEffect(()=>{const refresh=()=>setAssets(readAssets());window.addEventListener("apivoy-script-library-change",refresh);return()=>window.removeEventListener("apivoy-script-library-change",refresh)},[]);
 return <div className="script-steps"><div className="script-step-toolbar"><select aria-label="选择项目脚本" value={selected} onChange={(event)=>setSelected(event.target.value)} disabled={readOnly}><option value="">选择项目脚本…</option>{assets.map((asset)=><option key={asset.id} value={asset.id}>{asset.name} · {asset.language}</option>)}</select><button type="button" className="ui-button secondary" disabled={!selected||assetIds.includes(selected)||readOnly} onClick={()=>{onAssetIdsChange([...assetIds,selected]);setSelected("")}}>添加</button><button type="button" className="ui-button secondary" onClick={()=>window.dispatchEvent(new CustomEvent("apivoy-open-script-library"))}>管理脚本</button></div><div className="script-step-list">{assetIds.map((id,index)=>{const asset=assets.find((item)=>item.id===id);return <div key={id} draggable={!readOnly} onDragStart={()=>setDrag(index)} onDragOver={(event)=>event.preventDefault()} onDrop={()=>{if(drag===null||drag===index)return;const next=[...assetIds];const [item]=next.splice(drag,1);next.splice(index,0,item);onAssetIdsChange(next);setDrag(null)}}><Icon name="code"/><span><strong>{asset?.name??"脚本已缺失"}</strong><small>{asset?.language??"missing"}</small></span><button type="button" aria-label="上移" disabled={readOnly||index===0} onClick={()=>{const next=[...assetIds];[next[index-1],next[index]]=[next[index],next[index-1]];onAssetIdsChange(next)}}><Icon name="arrow-up"/></button><button type="button" aria-label="下移" disabled={readOnly||index===assetIds.length-1} onClick={()=>{const next=[...assetIds];[next[index+1],next[index]]=[next[index],next[index+1]];onAssetIdsChange(next)}}><Icon name="arrow-down"/></button><button type="button" aria-label="移除" disabled={readOnly} onClick={()=>onAssetIdsChange(assetIds.filter((item)=>item!==id))}><Icon name="close"/></button></div>})}</div>{assetIds.length===0?<div className="script-step-empty"><Icon name="code"/><strong>未添加{phase==="pre"?"前置":"后置"}脚本</strong><span>从项目脚本中选择，脚本内容统一在脚本管理中维护。</span></div>:null}</div>;
}
