import { useEffect, useRef, useState, type CSSProperties } from "react";
import { consumeHydrate } from "./openRequestPipeline";
import type { HttpRunResult, HttpSendHooks } from "./HttpWorkbench";
import { ProtocolCodeGenerator } from "./ProtocolCodeGenerator";
import { readWorkbenchDraft, useAutosaveDraft } from "./draftRecovery";

export interface SocketWorkbenchRequest { protocol: "tcp" | "udp"; name: string; target: string; data: string; encoding: "text" | "hex"; framing?: string | null; delimiter?: string | null; fixedLength?: number | null; sendCount: number; intervalMs: number; timeoutMs: number; tls: boolean; serverName?: string | null; caCertRef?: string | null }
export interface SocketWorkbenchProps { onSend: (request: SocketWorkbenchRequest, hooks?: HttpSendHooks) => Promise<HttpRunResult>; onCancel: (executionId: string) => Promise<void>; onSave?: (request: SocketWorkbenchRequest) => Promise<void>; externalRequest?: SocketWorkbenchRequest | null; tcpSessionUrl?: (target: string) => string }

export function SocketWorkbench({ onSend, onCancel, onSave, externalRequest, tcpSessionUrl }: SocketWorkbenchProps) {
  const [protocol, setProtocol] = useState<"tcp" | "udp">("tcp");
  const [target, setTarget] = useState("127.0.0.1:9000");
  const [data, setData] = useState("");
  const [encoding, setEncoding] = useState<"text" | "hex">("text");
  const [framing, setFraming] = useState("none");
  const [delimiter, setDelimiter] = useState("\\n");
  const [fixedLength, setFixedLength] = useState(1);
  const [sendCount, setSendCount] = useState(1);
  const [intervalMs, setIntervalMs] = useState(1000);
  const [timeoutMs, setTimeoutMs] = useState(3000);
  const [tls, setTls] = useState(false);
  const [serverName, setServerName] = useState("");
  const [caCertRef, setCaCertRef] = useState("");
  const [runningId, setRunningId] = useState<string | null>(null);
  const [output, setOutput] = useState("尚未发送");
  const [busy, setBusy] = useState(false);
  const [sessionOpen, setSessionOpen] = useState(false);
  const sessionRef = useRef<WebSocket | null>(null);
  useEffect(() => { const apply = (value: SocketWorkbenchRequest) => { setProtocol(value.protocol); setTarget(value.target); setData(value.data); setEncoding(value.encoding); setFraming(value.framing ?? "none"); setDelimiter(value.delimiter ?? "\\n"); setFixedLength(value.fixedLength ?? 1); setSendCount(value.sendCount); setIntervalMs(value.intervalMs); setTimeoutMs(value.timeoutMs); setTls(value.tls); setServerName(value.serverName ?? ""); setCaCertRef(value.caCertRef ?? ""); }; if (externalRequest) apply(externalRequest); else { const draft = readWorkbenchDraft<SocketWorkbenchRequest>("socket"); if (draft) apply(draft); } const listener = (event: Event) => { const envelope = (event as CustomEvent).detail; const payload = envelope?.payload; if (payload?.type !== "tcp" && payload?.type !== "udp") return; apply({ protocol: payload.type, name: envelope.name, target: envelope.target, data: payload.data, encoding: payload.encoding, framing: payload.type === "tcp" ? payload.framing : null, delimiter: payload.type === "tcp" ? payload.delimiter : null, fixedLength: payload.type === "tcp" ? payload.fixedLength : null, sendCount: payload.sendCount, intervalMs: payload.intervalMs, timeoutMs: envelope.timeoutMs, tls: payload.type === "tcp" && payload.tls, serverName: payload.type === "tcp" ? payload.serverName : null, caCertRef: payload.type === "tcp" ? payload.caCertRef : null }); }; const pending = consumeHydrate("socket"); if (pending) listener(new CustomEvent("apivoy-open-request", { detail: pending.envelope }) as Event); const onHydrate = (event: Event) => { const d = (event as CustomEvent).detail; if (d?.workbenchId !== "socket") return; listener(new CustomEvent("apivoy-open-request", { detail: d.envelope }) as Event); }; window.addEventListener("apivoy-open-request", listener); window.addEventListener("apivoy-hydrate-request", onHydrate); return () => { window.removeEventListener("apivoy-open-request", listener); window.removeEventListener("apivoy-hydrate-request", onHydrate); }; }, [externalRequest]);
  const request = (): SocketWorkbenchRequest => ({ protocol, name: `${protocol.toUpperCase()} ${target}`, target, data, encoding, framing: protocol === "tcp" ? framing : null, delimiter: framing === "delimiter" ? delimiter.replace(/\\n/g, "\n").replace(/\\r/g, "\r") : null, fixedLength: framing === "fixed" ? fixedLength : null, sendCount, intervalMs, timeoutMs, tls: protocol === "tcp" && tls, serverName: serverName || null, caCertRef: caCertRef || null });
  useAutosaveDraft("socket", request);
  async function send() {
    setBusy(true); setOutput("正在收发数据…");
    try { const result = await onSend(request(), { onStarted: setRunningId, onChunk: (chunk) => setOutput((current) => `${current}\n${chunk}`) }); setOutput(result.error ? `执行失败：${result.error}` : result.preview || `完成，收到 ${result.summary.bytesReceived} bytes`); }
    catch (error) { setOutput(error instanceof Error ? error.message : String(error)); }
    finally { setBusy(false); setRunningId(null); }
  }
  function openSession() { if (protocol !== "tcp" || sessionRef.current) return; setOutput("正在建立持久 TCP 会话…"); const fallback = `ws://127.0.0.1:39217/v1/tcp-session?target=${encodeURIComponent(target)}&token=${encodeURIComponent(localStorage.getItem("apivoy-agent-token") ?? "")}`; const socket = new WebSocket(tcpSessionUrl?.(target) ?? fallback); socket.binaryType = "arraybuffer"; socket.onopen = () => { sessionRef.current = socket; setSessionOpen(true); setOutput("TCP 会话已连接，可反复发送当前内容"); }; socket.onmessage = (event) => { const bytes = new Uint8Array(event.data as ArrayBuffer); const value = encoding === "hex" ? [...bytes].map((byte) => byte.toString(16).padStart(2, "0")).join(" ") : new TextDecoder().decode(bytes); setOutput((current) => `${current}\n← ${value}`); }; socket.onerror = () => setOutput((current) => `${current}\n连接错误`); socket.onclose = () => { sessionRef.current = null; setSessionOpen(false); setOutput((current) => `${current}\nTCP 会话已关闭`); }; }
  function sendSession() { const socket = sessionRef.current; if (!socket || socket.readyState !== WebSocket.OPEN) return; const bytes = encoding === "hex" ? Uint8Array.from(data.trim().split(/\s+/).filter(Boolean).map((item) => Number.parseInt(item, 16))) : new TextEncoder().encode(data); socket.send(bytes); setOutput((current) => `${current}\n→ ${data}`); }
  function closeSession() { sessionRef.current?.close(1000, "closed by user"); }
  useEffect(() => () => sessionRef.current?.close(1000, "workbench unmounted"), []);
  return <section style={styles.root}>
    <div style={styles.title}><div><small style={styles.eyebrow}>RAW SOCKET</small><h2 style={styles.h2}>TCP / UDP 调试</h2></div><select style={styles.select} value={protocol} onChange={(event) => setProtocol(event.target.value as "tcp" | "udp")}><option value="tcp">TCP</option><option value="udp">UDP</option></select></div>
    <div style={styles.row}><input style={styles.target} value={target} onChange={(event) => setTarget(event.target.value)} placeholder="host:port"/><select style={styles.select} value={encoding} onChange={(event) => setEncoding(event.target.value as "text" | "hex")}><option value="text">Text</option><option value="hex">Hex</option></select><button style={styles.send} disabled={busy} onClick={() => void send()}>发送</button>{onSave && <button style={styles.secondary} disabled={busy} onClick={() => void onSave(request())}>保存</button>}{runningId && <button style={styles.cancel} onClick={() => void onCancel(runningId)}>取消</button>}</div>
    {protocol === "tcp" && <div style={styles.options}><strong>持久交互会话</strong>{!sessionOpen ? <button style={styles.secondary} onClick={openSession}>建立连接</button> : <><button style={styles.send} onClick={sendSession}>发送当前内容</button><button style={styles.cancel} onClick={closeSession}>关闭连接</button></>}</div>}
    <textarea style={styles.data} value={data} onChange={(event) => setData(event.target.value)} placeholder={encoding === "hex" ? "48 65 6c 6c 6f" : "输入发送内容"}/>
    <div style={styles.options}>{protocol === "tcp" && <><label>分帧<select value={framing} onChange={(event) => setFraming(event.target.value)}><option value="none">关闭/超时</option><option value="delimiter">分隔符</option><option value="fixed">固定长度</option></select></label>{framing === "delimiter" && <label>分隔符<input value={delimiter} onChange={(event) => setDelimiter(event.target.value)}/></label>}{framing === "fixed" && <label>长度<input type="number" min={1} value={fixedLength} onChange={(event) => setFixedLength(+event.target.value)}/></label>}<label><input type="checkbox" checked={tls} onChange={(event) => setTls(event.target.checked)}/>TLS</label>{tls && <><label>SNI<input value={serverName} onChange={(event) => setServerName(event.target.value)} placeholder="默认使用目标主机"/></label><label>自定义 CA 密钥引用<input value={caCertRef} onChange={(event) => setCaCertRef(event.target.value)} placeholder="可选 PEM"/></label></>}</>}<label>发送次数<input type="number" min={1} value={sendCount} onChange={(event) => setSendCount(+event.target.value)}/></label><label>间隔 ms<input type="number" min={0} value={intervalMs} onChange={(event) => setIntervalMs(+event.target.value)}/></label><label>接收超时 ms<input type="number" min={1} value={timeoutMs} onChange={(event) => setTimeoutMs(+event.target.value)}/></label></div>
    <ProtocolCodeGenerator input={{ protocol, request: request() }} />
    <pre style={styles.output}>{output}</pre>
  </section>;
}

const styles: Record<string, CSSProperties> = { root: { marginTop: 22, padding: 18, border: "1px solid var(--apivoy-border)", borderRadius: 14, background: "#0c131c" }, title: { display: "flex", justifyContent: "space-between", alignItems: "center" }, eyebrow: { color: "#c398ff", letterSpacing: 1.4 }, h2: { margin: "3px 0 14px", fontSize: 18 }, row: { display: "flex", gap: 8 }, target: { flex: 1, minWidth: 0, background: "#080d13", color: "var(--apivoy-text)", border: "1px solid var(--apivoy-border)", borderRadius: 8, padding: 10 }, select: { background: "#111a25", color: "var(--apivoy-text)", border: "1px solid var(--apivoy-border)", borderRadius: 8, padding: "8px 10px" }, send: { border: 0, borderRadius: 8, background: "#9c72e8", color: "#10091d", fontWeight: 700, padding: "0 18px" }, secondary: { border: "1px solid var(--apivoy-border)", borderRadius: 8, background: "#151d28", color: "var(--apivoy-text)", padding: "0 12px" }, cancel: { border: "1px solid #71434a", borderRadius: 8, background: "#2b171b", color: "#ff9ca8" }, data: { boxSizing: "border-box", width: "100%", minHeight: 100, marginTop: 10, resize: "vertical", background: "#080d13", color: "#cfe1ef", border: "1px solid var(--apivoy-border)", borderRadius: 8, padding: 10, fontFamily: "monospace" }, options: { display: "flex", flexWrap: "wrap", gap: 12, marginTop: 10, color: "var(--apivoy-muted)", fontSize: 11 }, output: { minHeight: 70, maxHeight: 260, overflow: "auto", whiteSpace: "pre-wrap", background: "#070b10", border: "1px solid var(--apivoy-border)", borderRadius: 8, padding: 10, color: "#b9d5e8" } };
