import { useEffect, useState, type CSSProperties } from "react";
import { consumeHydrate } from "./openRequestPipeline";
import type { HttpRunResult, HttpSendHooks } from "./HttpWorkbench";
import { ProtocolWorkbenchLayout } from "./ProtocolWorkbenchLayout";
export interface SqlWorkbenchRequest{name:string;target:string;username:string;passwordRef:string;sql:string;parameters:unknown[];transactional:boolean;rowLimit:number;timeoutMs:number}
export interface SqlWorkbenchProps{onSend:(request:SqlWorkbenchRequest,hooks?:HttpSendHooks)=>Promise<HttpRunResult>;onSave?:(request:SqlWorkbenchRequest)=>Promise<void>;onCancel?:(executionId:string)=>Promise<void>}
export function SqlWorkbench({onSend,onSave,onCancel}:SqlWorkbenchProps){
 const[name,setName]=useState("SQL query"),[target,setTarget]=useState("sqlite::memory:"),[username,setUsername]=useState(""),[passwordRef,setPasswordRef]=useState(""),[sql,setSql]=useState("SELECT 42 AS answer"),[parameters,setParameters]=useState("[]"),[transactional,setTransactional]=useState(false),[rowLimit,setRowLimit]=useState(500),[result,setResult]=useState<HttpRunResult|null>(null),[message,setMessage]=useState(""),[loading,setLoading]=useState(false),[executionId,setExecutionId]=useState<string|null>(null);
 useEffect(()=>{const listener=(event:Event)=>{const e=(event as CustomEvent).detail;if(e?.protocolId!=="sql"||e.payload?.type!=="raw")return;const v=e.payload.value??e.payload;setName(e.name);setTarget(e.target);setUsername(v.username??"");setPasswordRef(v.passwordRef??"");setSql(v.sql??"");setParameters(JSON.stringify(v.parameters??[],null,2));setTransactional(v.transactional??false);setRowLimit(v.rowLimit??500)};const pending=consumeHydrate("sql");if(pending)listener(new CustomEvent("apivoy-open-request",{detail:pending.envelope})as Event);const hydrate=(event:Event)=>{const d=(event as CustomEvent).detail;if(d?.workbenchId==="sql")listener(new CustomEvent("apivoy-open-request",{detail:d.envelope})as Event)};window.addEventListener("apivoy-open-request",listener);window.addEventListener("apivoy-hydrate-request",hydrate);return()=>{window.removeEventListener("apivoy-open-request",listener);window.removeEventListener("apivoy-hydrate-request",hydrate)}},[]);
 const build=():SqlWorkbenchRequest=>{const parsed=JSON.parse(parameters||"[]");if(!Array.isArray(parsed))throw new Error("参数必须是 JSON 数组");return{name,target,username,passwordRef,sql,parameters:parsed,transactional,rowLimit,timeoutMs:30000}};
 async function run(){setLoading(true);setResult(null);setMessage("");try{setResult(await onSend(build(),{onStarted:setExecutionId,onChunk:()=>{}}))}catch(e){setMessage(e instanceof Error?e.message:String(e))}finally{setLoading(false);setExecutionId(null)}}
 async function save(){if(!onSave)return;try{await onSave(build());setMessage("已保存到集合")}catch(e){setMessage(e instanceof Error?e.message:String(e))}}
 const engine=target.startsWith("postgres")?"PostgreSQL":target.startsWith("mysql")?"MySQL":"SQLite";
 return <ProtocolWorkbenchLayout id="sql" protocol={engine.toUpperCase()} name={name} target={target} targetLabel="数据库连接地址" actionLabel="Run query" loadingLabel="执行中…" loading={loading} result={result} responseTitle="Result set" emptyResponse="列、结果行、影响行数与插入 ID 会显示在这里" message={message} onNameChange={setName} onTargetChange={setTarget} onRun={()=>void run()} onSave={onSave?()=>void save():undefined} onCancel={onCancel&&executionId?()=>void onCancel(executionId):undefined}>
  <div><div style={s.credentials}><label style={s.label}>USERNAME<input style={s.input} value={username} onChange={e=>setUsername(e.target.value)} disabled={engine==="SQLite"}/></label><label style={s.label}>PASSWORD SECRET REF<input style={s.input} value={passwordRef} onChange={e=>setPasswordRef(e.target.value)} disabled={engine==="SQLite"}/></label><label style={s.label}>ROW LIMIT<input style={s.input} type="number" min={1} max={10000} value={rowLimit} onChange={e=>setRowLimit(Math.max(1,Math.min(10000,Number(e.target.value))))}/></label></div><label style={s.label}>SQL<textarea style={s.editor} value={sql} onChange={e=>setSql(e.target.value)} spellCheck={false}/></label><label style={s.label}>PARAMETERS · JSON ARRAY<textarea style={s.params} value={parameters} onChange={e=>setParameters(e.target.value)} spellCheck={false}/></label><label style={s.check}><input type="checkbox" checked={transactional} onChange={e=>setTransactional(e.target.checked)}/> Execute in transaction</label></div>
 </ProtocolWorkbenchLayout>}
const s:Record<string,CSSProperties>={credentials:{display:"grid",gridTemplateColumns:"1fr 1.3fr 100px",gap:8},label:{display:"grid",gap:6,color:"var(--apivoy-muted)",fontSize:10,fontWeight:750,marginBottom:10},input:{width:"100%",border:"1px solid var(--apivoy-border)",borderRadius:8,padding:9,background:"var(--apivoy-bg-elevated)",color:"var(--apivoy-text)"},editor:{width:"100%",minHeight:210,border:"1px solid var(--apivoy-border)",borderRadius:9,padding:12,background:"var(--apivoy-bg)",color:"var(--apivoy-text)",fontFamily:"var(--apivoy-mono)",lineHeight:1.55},params:{width:"100%",minHeight:80,border:"1px solid var(--apivoy-border)",borderRadius:9,padding:10,background:"var(--apivoy-bg)",color:"var(--apivoy-text)",fontFamily:"var(--apivoy-mono)"},check:{color:"var(--apivoy-muted)",fontSize:11}};
