import { useEffect, useState, type CSSProperties } from "react";
import { defaultCollaborationUrl } from "./runtimeConfig";

type Auth = { token: string; expiresAt: string; organizationId: string; role: string; user: { id: string; email: string; displayName: string } };
type Config = { enabled: boolean; loginPath?: string };

export function SsoWorkbench() {
  const [baseUrl, setBaseUrl] = useState(() => localStorage.getItem("apivoy:collaboration-url") ?? defaultCollaborationUrl());
  const [config, setConfig] = useState<Config | null>(null);
  const [message, setMessage] = useState("");
  const [connected, setConnected] = useState<Auth | null>(null);

  useEffect(() => {
    const auth = consumeCallback();
    if (auth) { localStorage.setItem("apivoy:collaboration-auth", JSON.stringify(auth)); setConnected(auth); setMessage("企业身份验证成功，正在载入团队空间…"); queueMicrotask(()=>location.reload()); }
  }, []);
  useEffect(() => { localStorage.setItem("apivoy:collaboration-url", baseUrl); const controller=new AbortController(); setConfig(null); fetch(`${baseUrl.replace(/\/$/,"")}/v1/auth/sso/config`,{signal:controller.signal}).then(async response=>{if(!response.ok)throw new Error(`HTTP ${response.status}`);setConfig(await response.json() as Config);setMessage("");}).catch(error=>{if(error instanceof DOMException&&error.name==="AbortError")return;setMessage(error instanceof Error?error.message:String(error));}); return ()=>controller.abort(); }, [baseUrl]);

  function login(){if(config?.loginPath)window.location.assign(`${baseUrl.replace(/\/$/,"")}${config.loginPath}`);}
  return <section style={styles.root}><header style={styles.header}><div><small style={styles.eyebrow}>ENTERPRISE IDENTITY</small><h2 style={styles.title}>单点登录</h2><p style={styles.copy}>使用企业 OIDC 身份进入团队空间。ApiVoy 仅接受 IdP 已验证的邮箱，并按组织策略分配最低权限。</p></div><span style={{...styles.badge,...(config?.enabled?styles.online:styles.offline)}}>{config?.enabled?"OIDC READY":"NOT CONFIGURED"}</span></header><div style={styles.grid}><div style={styles.card}><span style={styles.number}>01</span><h3>连接协作服务</h3><label style={styles.label}>COLLABORATION URL<input style={styles.input} value={baseUrl} onChange={event=>setBaseUrl(event.target.value)} /></label></div><div style={styles.card}><span style={styles.number}>02</span><h3>验证企业身份</h3><p style={styles.muted}>{config?.enabled?"服务已启用 OIDC。点击后将跳转到组织身份提供商。":"管理员尚未为该服务配置 OIDC，仍可在 Team 中使用本地账号登录。"}</p><button style={styles.primary} disabled={!config?.enabled} onClick={login}>使用企业账号继续</button></div><div style={styles.card}><span style={styles.number}>03</span><h3>进入团队空间</h3>{connected?<div style={styles.identity}><span style={styles.avatar}>{connected.user.displayName.slice(0,1).toUpperCase()}</span><div><b>{connected.user.displayName}</b><small>{connected.user.email} · {connected.role}</small></div></div>:<p style={styles.muted}>认证完成后，登录态会安全交给 Team 和 Comments 工作台。</p>}</div></div>{message&&<div style={styles.notice}>{message}</div>}</section>;
}

function consumeCallback():Auth|null { const match=location.hash.match(/(?:^#|&)apivoy_sso=([^&]+)/); if(!match)return null; try { const binary=atob(match[1].replace(/-/g,"+").replace(/_/g,"/")); const bytes=Uint8Array.from(binary,char=>char.charCodeAt(0)); const auth=JSON.parse(new TextDecoder().decode(bytes)) as Auth; history.replaceState(null,"",`${location.pathname}${location.search}`); return auth; } catch { return null; } }

const styles:Record<string,CSSProperties>={root:{border:"1px solid var(--apivoy-border)",borderRadius:18,background:"radial-gradient(700px 360px at 90% -10%,rgba(102,89,255,.16),transparent 58%),linear-gradient(150deg,rgba(18,27,38,.97),rgba(8,13,20,.99))",padding:24,minHeight:500},header:{display:"flex",justifyContent:"space-between",gap:20,alignItems:"flex-start",marginBottom:28},eyebrow:{letterSpacing:2,color:"#9fa7ff",fontSize:10,fontWeight:800},title:{fontSize:28,margin:"5px 0 8px",letterSpacing:-.8},copy:{color:"var(--apivoy-muted)",lineHeight:1.7,maxWidth:650,margin:0},badge:{fontSize:10,letterSpacing:1.2,borderRadius:999,padding:"7px 11px",fontWeight:800},online:{color:"#79ddb7",border:"1px solid rgba(73,207,158,.35)",background:"rgba(73,207,158,.09)"},offline:{color:"#a3afbd",border:"1px solid var(--apivoy-border)",background:"rgba(255,255,255,.03)"},grid:{display:"grid",gridTemplateColumns:"repeat(3,minmax(0,1fr))",gap:13},card:{border:"1px solid var(--apivoy-border)",borderRadius:14,background:"rgba(5,10,16,.52)",padding:18,minHeight:210},number:{color:"#7f8cff",fontFamily:"var(--apivoy-mono)",fontSize:11},label:{display:"grid",gap:7,color:"var(--apivoy-muted)",fontSize:10,fontWeight:700,marginTop:20},input:{width:"100%",border:"1px solid var(--apivoy-border)",borderRadius:9,background:"#090f17",color:"var(--apivoy-text)",padding:"10px 11px",outline:"none"},muted:{color:"var(--apivoy-muted)",lineHeight:1.65,minHeight:68},primary:{border:0,borderRadius:9,background:"linear-gradient(135deg,#6659ff,#319fc9)",color:"white",fontWeight:750,padding:"10px 14px",cursor:"pointer"},notice:{marginTop:16,borderLeft:"3px solid #8177ff",background:"rgba(102,89,255,.09)",padding:"10px 13px",fontSize:12},identity:{display:"flex",gap:11,alignItems:"center",marginTop:28},avatar:{width:42,height:42,borderRadius:12,display:"grid",placeItems:"center",fontWeight:800,background:"linear-gradient(135deg,rgba(102,89,255,.35),rgba(49,159,201,.25))"}};
