package dev.apivoy.collaboration;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpStatus;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.transaction.support.TransactionSynchronization;
import org.springframework.transaction.support.TransactionSynchronizationManager;
import org.springframework.web.server.ResponseStatusException;
import java.time.*;
import java.util.*;

@Service
class CollaborationService {
    private final UserRepository users; private final FederatedIdentityRepository identities; private final OrganizationRepository organizations; private final MembershipRepository memberships; private final SessionRepository sessions; private final WorkspaceRepository workspaces; private final ChangeRepository changes; private final AuditRepository audits; private final CommentRepository comments; private final PasswordEncoder passwords; private final ObjectMapper json; private final WorkspaceEventHub events; private final String bootstrapToken;
    CollaborationService(UserRepository users, FederatedIdentityRepository identities, OrganizationRepository organizations, MembershipRepository memberships, SessionRepository sessions, WorkspaceRepository workspaces, ChangeRepository changes, AuditRepository audits, CommentRepository comments, PasswordEncoder passwords, ObjectMapper json, WorkspaceEventHub events, @Value("${apivoy.bootstrap-token}") String bootstrapToken) { this.users=users; this.identities=identities; this.organizations=organizations; this.memberships=memberships; this.sessions=sessions; this.workspaces=workspaces; this.changes=changes; this.audits=audits; this.comments=comments; this.passwords=passwords; this.json=json; this.events=events; this.bootstrapToken=bootstrapToken; }

    @Transactional AuthResult bootstrap(String supplied, String email, String password, String displayName, String organizationName, String deviceName) {
        if (!Objects.equals(bootstrapToken, supplied) || users.count() > 0) throw new ResponseStatusException(HttpStatus.FORBIDDEN, "bootstrap is unavailable");
        validatePassword(password); var user=users.save(new UserAccount(normalizeEmail(email), displayName.trim(), passwords.encode(password))); var organization=organizations.save(new Organization(organizationName.trim())); memberships.save(new Membership(organization.id, user.id, Role.OWNER)); audit(organization.id,user.id,"organization.bootstrap","organization",organization.id,"{}"); return session(user,deviceName,organization.id,Role.OWNER);
    }
    @Transactional AuthResult login(String email,String password,String deviceName) { var user=users.findByEmailIgnoreCase(normalizeEmail(email)).orElseThrow(() -> unauthorized()); if(!passwords.matches(password,user.passwordHash)) throw unauthorized(); var membership=memberships.findByUserId(user.id).stream().findFirst().orElseThrow(() -> new ResponseStatusException(HttpStatus.FORBIDDEN,"no organization membership")); return session(user,deviceName,membership.organizationId,membership.role); }
    @Transactional AuthResult ssoLogin(String provider,String subject,String email,boolean emailVerified,String displayName,String organizationId,Role defaultRole,String deviceName) {
        if(!emailVerified) throw new ResponseStatusException(HttpStatus.FORBIDDEN,"OIDC provider did not verify the email address");
        if(defaultRole==Role.OWNER||defaultRole==Role.ADMIN) throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"SSO default role cannot grant administrative access");
        var organization=organizations.findById(organizationId).orElseThrow(()->new ResponseStatusException(HttpStatus.FORBIDDEN,"SSO organization is unavailable"));
        String normalized=normalizeEmail(email);
        var identity=identities.findByProviderAndSubject(provider,subject).orElse(null);
        UserAccount user;
        if(identity!=null) user=users.findById(identity.userId).orElseThrow(()->new ResponseStatusException(HttpStatus.UNAUTHORIZED,"federated identity is invalid"));
        else {
            user=users.findByEmailIgnoreCase(normalized).orElseGet(()->users.save(new UserAccount(normalized,displayName==null||displayName.isBlank()?normalized:displayName.trim(),passwords.encode(UUID.randomUUID().toString()+UUID.randomUUID()))));
            identities.save(new FederatedIdentity(provider,subject,user.id));
        }
        var membership=memberships.findByOrganizationIdAndUserId(organization.id,user.id).orElseGet(()->memberships.save(new Membership(organization.id,user.id,defaultRole)));
        audit(organization.id,user.id,"auth.sso","federated_identity",provider,"{\"provider\":\""+provider+"\"}");
        return session(user,deviceName,organization.id,membership.role);
    }
    @Transactional void logout(String rawToken) { sessions.findByTokenHashAndRevokedAtIsNullAndExpiresAtAfter(SecurityConfig.hash(rawToken),Instant.now()).ifPresent(value -> value.revokedAt=Instant.now()); }
    List<OrganizationView> organizations(String userId) { return memberships.findByUserId(userId).stream().map(m -> { var org=organizations.findById(m.organizationId).orElseThrow(); return new OrganizationView(org.id,org.name,m.role); }).toList(); }
    List<MemberView> members(String actor,String organizationId) { require(actor,organizationId,Role.VIEWER); return memberships.findAll().stream().filter(m->m.organizationId.equals(organizationId)).map(m->{var u=users.findById(m.userId).orElseThrow(); return new MemberView(u.id,u.email,u.displayName,m.role);}).toList(); }
    @Transactional MemberView addMember(String actor,String organizationId,String email,Role role) { require(actor,organizationId,Role.ADMIN); if(role==Role.OWNER) require(actor,organizationId,Role.OWNER); var user=users.findByEmailIgnoreCase(normalizeEmail(email)).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"user not found")); var member=memberships.findByOrganizationIdAndUserId(organizationId,user.id).orElseGet(()->new Membership(organizationId,user.id,role)); member.role=role; memberships.save(member); audit(organizationId,actor,"member.upsert","user",user.id,"{\"role\":\""+role+"\"}"); return new MemberView(user.id,user.email,user.displayName,role); }
    @Transactional MemberView provisionMember(String actor,String organizationId,String email,String displayName,String password,Role role) { require(actor,organizationId,Role.ADMIN); if(role==Role.OWNER) require(actor,organizationId,Role.OWNER); validatePassword(password); String normalized=normalizeEmail(email); if(users.findByEmailIgnoreCase(normalized).isPresent()) throw new ResponseStatusException(HttpStatus.CONFLICT,"user already exists"); var user=users.save(new UserAccount(normalized,displayName.trim(),passwords.encode(password))); memberships.save(new Membership(organizationId,user.id,role)); audit(organizationId,actor,"member.provision","user",user.id,"{\"role\":\""+role+"\"}"); return new MemberView(user.id,user.email,user.displayName,role); }
    @Transactional WorkspaceView push(String actor,String organizationId,String workspaceId,long baseRevision,JsonNode document,JsonNode patch) { require(actor,organizationId,Role.EDITOR); var state=workspaces.findByOrganizationIdAndWorkspaceId(organizationId,workspaceId).orElseGet(()->new WorkspaceState(organizationId,workspaceId,"{}",actor)); if(state.revision!=baseRevision) throw new ConflictException(state.revision,state.documentJson); state.revision++; state.documentJson=write(document); state.updatedBy=actor; state.updatedAt=Instant.now(); workspaces.saveAndFlush(state); changes.saveAndFlush(new WorkspaceChange(organizationId,workspaceId,state.revision,write(patch),actor)); audit(organizationId,actor,"workspace.sync","workspace",workspaceId,"{\"revision\":"+state.revision+"}"); long revision=state.revision; TransactionSynchronizationManager.registerSynchronization(new TransactionSynchronization(){@Override public void afterCommit(){events.publish(organizationId,workspaceId,revision,actor);}}); return view(state); }
    org.springframework.web.servlet.mvc.method.annotation.SseEmitter subscribe(String actor,String organizationId) { require(actor,organizationId,Role.VIEWER); return events.subscribe(organizationId); }
    WorkspaceView workspace(String actor,String organizationId,String workspaceId) { require(actor,organizationId,Role.VIEWER); return workspaces.findByOrganizationIdAndWorkspaceId(organizationId,workspaceId).map(this::view).orElse(new WorkspaceView(workspaceId,0,json.createObjectNode(),null,null)); }
    List<ChangeView> changes(String actor,String organizationId,String workspaceId,long after) { require(actor,organizationId,Role.VIEWER); return changes.findByOrganizationIdAndWorkspaceIdAndRevisionGreaterThanOrderByRevision(organizationId,workspaceId,after).stream().map(c->new ChangeView(c.revision,read(c.patchJson),c.actorId,c.createdAt)).toList(); }
    List<AuditView> audits(String actor,String organizationId) { require(actor,organizationId,Role.ADMIN); return audits.findTop200ByOrganizationIdOrderByCreatedAtDesc(organizationId).stream().map(a->new AuditView(a.id,a.actorId,a.action,a.resourceType,a.resourceId,read(a.detailsJson),a.createdAt)).toList(); }
    List<CommentView> comments(String actor,String organizationId,String workspaceId) { require(actor,organizationId,Role.VIEWER); return comments.findByOrganizationIdAndWorkspaceIdOrderByCreatedAt(organizationId,workspaceId).stream().map(this::commentView).toList(); }
    @Transactional CommentView addComment(String actor,String organizationId,String workspaceId,String parentId,String body) { require(actor,organizationId,Role.VIEWER); String text=commentBody(body); if(parentId!=null){var parent=comments.findById(parentId).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"parent comment not found"));if(!parent.organizationId.equals(organizationId)||!parent.workspaceId.equals(workspaceId))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"parent comment belongs to another workspace");} var comment=comments.save(new WorkspaceComment(organizationId,workspaceId,actor,parentId,text)); audit(organizationId,actor,"comment.create","workspace_comment",comment.id,"{\"workspaceId\":\""+workspaceId+"\"}"); events.publishComment(organizationId,workspaceId,comment.id,"created",actor); return commentView(comment); }
    @Transactional CommentView editComment(String actor,String organizationId,String workspaceId,String commentId,String body) { var membership=require(actor,organizationId,Role.VIEWER); var comment=findComment(organizationId,workspaceId,commentId); if(!comment.actorId.equals(actor)&&rank(membership.role)>rank(Role.ADMIN))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"only the author or an admin can edit this comment"); comment.body=commentBody(body);comment.updatedAt=Instant.now();audit(organizationId,actor,"comment.edit","workspace_comment",comment.id,"{}");events.publishComment(organizationId,workspaceId,comment.id,"edited",actor);return commentView(comment); }
    @Transactional CommentView resolveComment(String actor,String organizationId,String workspaceId,String commentId,boolean resolved) { require(actor,organizationId,Role.EDITOR); var comment=findComment(organizationId,workspaceId,commentId);comment.resolvedAt=resolved?Instant.now():null;comment.resolvedBy=resolved?actor:null;comment.updatedAt=Instant.now();audit(organizationId,actor,resolved?"comment.resolve":"comment.reopen","workspace_comment",comment.id,"{}");events.publishComment(organizationId,workspaceId,comment.id,resolved?"resolved":"reopened",actor);return commentView(comment); }
    private Membership require(String userId,String organizationId,Role minimum) { var m=memberships.findByOrganizationIdAndUserId(organizationId,userId).orElseThrow(()->new ResponseStatusException(HttpStatus.FORBIDDEN,"not a member")); if(rank(m.role)>rank(minimum)) throw new ResponseStatusException(HttpStatus.FORBIDDEN,"insufficient role"); return m; }
    private int rank(Role role){ return List.of(Role.OWNER,Role.ADMIN,Role.EDITOR,Role.RUNNER,Role.VIEWER).indexOf(role); }
    private AuthResult session(UserAccount user,String device,String orgId,Role role){ String token=UUID.randomUUID()+"."+UUID.randomUUID(); Instant expires=Instant.now().plus(Duration.ofDays(30)); sessions.save(new DeviceSession(user.id,SecurityConfig.hash(token),device==null?"unknown":device,expires)); return new AuthResult(token,expires,new UserView(user.id,user.email,user.displayName),orgId,role); }
    private void audit(String org,String actor,String action,String type,String id,String details){audits.save(new AuditEvent(org,actor,action,type,id,details));}
    private WorkspaceView view(WorkspaceState s){return new WorkspaceView(s.workspaceId,s.revision,read(s.documentJson),s.updatedBy,s.updatedAt);}
    private WorkspaceComment findComment(String organizationId,String workspaceId,String commentId){var value=comments.findById(commentId).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"comment not found"));if(!value.organizationId.equals(organizationId)||!value.workspaceId.equals(workspaceId))throw new ResponseStatusException(HttpStatus.NOT_FOUND,"comment not found");return value;}
    private String commentBody(String body){if(body==null||body.trim().isEmpty())throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"comment body is required");String text=body.trim();if(text.length()>4000)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"comment body exceeds 4000 characters");return text;}
    private CommentView commentView(WorkspaceComment value){var user=users.findById(value.actorId).orElse(null);return new CommentView(value.id,value.workspaceId,value.actorId,user==null?"Unknown":user.displayName,value.parentId,value.body,value.resolvedAt,value.resolvedBy,value.createdAt,value.updatedAt);}
    private JsonNode read(String value){try{return json.readTree(value==null?"{}":value);}catch(Exception e){throw new IllegalStateException(e);}}
    private String write(JsonNode value){try{return json.writeValueAsString(value==null?json.createObjectNode():value);}catch(Exception e){throw new IllegalArgumentException("invalid JSON",e);}}
    private String normalizeEmail(String email){if(email==null||!email.contains("@"))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"valid email required");return email.trim().toLowerCase(Locale.ROOT);}
    private void validatePassword(String password){if(password==null||password.length()<10)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"password must contain at least 10 characters");}
    private ResponseStatusException unauthorized(){return new ResponseStatusException(HttpStatus.UNAUTHORIZED,"invalid credentials");}
    record AuthResult(String token,Instant expiresAt,UserView user,String organizationId,Role role){} record UserView(String id,String email,String displayName){} record OrganizationView(String id,String name,Role role){} record MemberView(String id,String email,String displayName,Role role){} record WorkspaceView(String workspaceId,long revision,JsonNode document,String updatedBy,Instant updatedAt){} record ChangeView(long revision,JsonNode patch,String actorId,Instant createdAt){} record AuditView(String id,String actorId,String action,String resourceType,String resourceId,JsonNode details,Instant createdAt){} record CommentView(String id,String workspaceId,String actorId,String actorName,String parentId,String body,Instant resolvedAt,String resolvedBy,Instant createdAt,Instant updatedAt){}
}

class ConflictException extends RuntimeException { final long revision; final String document; ConflictException(long revision,String document){super("workspace revision conflict");this.revision=revision;this.document=document;} }
