[package]
name = "apivoy-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "ApiVoy CLI runner"

[[bin]]
name = "apivoy-cli"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
csv = "1"
driver-http = { workspace = true }
driver-sse = { workspace = true }
driver-tcp-udp = { workspace = true }
driver-graphql = { workspace = true }
driver-websocket = { workspace = true }
driver-grpc = { workspace = true }
driver-rpc-http = { workspace = true }
driver-redis = { workspace = true }
driver-mqtt = { workspace = true }
driver-amqp = { workspace = true }
driver-kafka = { workspace = true }
core-domain = { workspace = true }
execution-engine = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "sync", "time", "signal"] }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
